import { DEFAULT_LANGUAGE, ROLE_DASHBOARD_SEGMENTS } from '@/lib/constants'
import type { SupportedLanguage } from '@/hooks/useLanguage'
import type { UserRole } from '@/types/user.types'

export const routePaths = {
  root: '/',
  login: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/login`,
  errors: {
    notFound: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/not-found`,
    accessDenied: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/access-denied`,
    accountDisabled: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/account-disabled`,
    serverError: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/server-error`,
  },
  managerParent: {
    root: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/dashboard`,
    dashboard: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/dashboard`,
    teamManagement: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/team-management`,
    teamMemberDetail: (lang: SupportedLanguage = DEFAULT_LANGUAGE, id: number | string = ':id') => `/${lang}/team-management/${id}`,
    teamNetwork: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/team-network`,
    software: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/software`,
    softwareManagement: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/software-management`,
    programCreate: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/software-management/create`,
    programEdit: (lang: SupportedLanguage = DEFAULT_LANGUAGE, id: number | string = ':id') => `/${lang}/software-management/${id}/edit`,
    activateLicense: (lang: SupportedLanguage = DEFAULT_LANGUAGE, id: number | string = ':id') => `/${lang}/software-management/${id}/activate`,
    biosBlacklist: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/bios-blacklist`,
    biosHistory: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/bios-history`,
    biosDetails: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/bios-details`,
    biosDetail: (lang: SupportedLanguage = DEFAULT_LANGUAGE, biosId: string | number = ':biosId') => `/${lang}/bios-details/${encodeURIComponent(String(biosId))}`,
    biosChangeRequests: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/bios-change-requests`,
    biosChangeAudit: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/bios-change-audit`,
    resellerPayments: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/reseller-payments`,
    resellerPaymentDetail: (lang: SupportedLanguage = DEFAULT_LANGUAGE, resellerId: number | string = ':resellerId') => `/${lang}/reseller-payments/${resellerId}`,
    resellerPaymentsManagerParentCustomers: (lang: SupportedLanguage = DEFAULT_LANGUAGE, managerParentId: number | string = ':managerParentId') => `/${lang}/reseller-payments/manager-parent/${managerParentId}/customers`,
    biosConflicts: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/bios-conflicts`,
    ipAnalytics: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/ip-analytics`,
    logs: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/logs`,
    programLogs: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/program-logs`,
    resellerLogs: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/reseller-logs`,
    apiStatus: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/api-status`,
    usernameManagement: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/team-management`,
    financialReports: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/reports`,
    reports: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/reports`,
    activity: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/activity`,
    customers: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/customers`,
    customerCreate: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/customers/create`,
    licenseRenew: (lang: SupportedLanguage = DEFAULT_LANGUAGE, id: number | string = ':id') => `/${lang}/customers/licenses/${id}/renew`,
    licenses: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/customers`,
    customerDetail: (lang: SupportedLanguage = DEFAULT_LANGUAGE, id: number | string = ':id') => `/${lang}/customers/${id}`,
    settings: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/settings`,
    profile: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/profile`,
  },
  manager: {
    root: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/manager`,
    dashboard: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/manager/dashboard`,
    team: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/manager/team`,
    teamMemberDetail: (lang: SupportedLanguage = DEFAULT_LANGUAGE, id: number | string = ':id') => `/${lang}/manager/team/${id}`,
    usernameManagement: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/manager/team`,
    software: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/manager/software`,
    customers: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/manager/customers`,
    customerCreate: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/manager/customers/create`,
    licenseRenew: (lang: SupportedLanguage = DEFAULT_LANGUAGE, id: number | string = ':id') => `/${lang}/manager/customers/licenses/${id}/renew`,
    customerDetail: (lang: SupportedLanguage = DEFAULT_LANGUAGE, id: number | string = ':id') => `/${lang}/manager/customers/${id}`,
    customerBiosChangeRequest: (lang: SupportedLanguage = DEFAULT_LANGUAGE, id: number | string = ':id') => `/${lang}/manager/customers/${id}/request-bios-change`,
    licenses: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/manager/customers`,
    biosDetails: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/manager/bios-details`,
    biosDetail: (lang: SupportedLanguage = DEFAULT_LANGUAGE, biosId: string | number = ':biosId') => `/${lang}/manager/bios-details/${encodeURIComponent(String(biosId))}`,
    biosChangeRequests: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/manager/bios-change-requests`,
    resellerPayments: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/manager/reseller-payments`,
    resellerPaymentDetail: (lang: SupportedLanguage = DEFAULT_LANGUAGE, resellerId: number | string = ':resellerId') => `/${lang}/manager/reseller-payments/${resellerId}`,
    reports: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/manager/reports`,
    activity: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/manager/activity`,
    resellerLogs: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/manager/reseller-logs`,
    profile: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/manager/profile`,
  },
  reseller: {
    root: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/reseller`,
    dashboard: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/reseller/dashboard`,
    customers: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/reseller/customers`,
    customerCreate: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/reseller/customers/create`,
    licenseRenew: (lang: SupportedLanguage = DEFAULT_LANGUAGE, id: number | string = ':id') => `/${lang}/reseller/customers/licenses/${id}/renew`,
    customerDetail: (lang: SupportedLanguage = DEFAULT_LANGUAGE, id: number | string = ':id') => `/${lang}/reseller/customers/${id}`,
    customerBiosChangeRequest: (lang: SupportedLanguage = DEFAULT_LANGUAGE, id: number | string = ':id') => `/${lang}/reseller/customers/${id}/request-bios-change`,
    ipAnalytics: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/reseller/ip-analytics`,
    licenses: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/reseller/customers`,
    activations: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/reseller/activations`,
    resellerLogs: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/reseller/reseller-logs`,
    software: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/reseller/software`,
    activateLicense: (lang: SupportedLanguage = DEFAULT_LANGUAGE, id: number | string = ':id') => `/${lang}/reseller/software/${id}/activate`,
    paymentStatus: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/reseller/payment-status`,
    reports: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/reseller/reports`,
    profile: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/reseller/profile`,
  },
  customer: {
    root: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/customer`,
    dashboard: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/customer/dashboard`,
    software: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/customer/software`,
    download: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/customer/download`,
  },
  superAdmin: {
    root: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/super-admin`,
    dashboard: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/super-admin/dashboard`,
    tenants: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/super-admin/tenants`,
    customers: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/super-admin/customers`,
    customerCreate: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/super-admin/customers/create`,
    licenseRenew: (lang: SupportedLanguage = DEFAULT_LANGUAGE, id: number | string = ':id') => `/${lang}/super-admin/customers/licenses/${id}/renew`,
    customerDetail: (lang: SupportedLanguage = DEFAULT_LANGUAGE, id: number | string = ':id') => `/${lang}/super-admin/customers/${id}`,
    deletedCustomers: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/super-admin/deleted-customers`,
    users: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/super-admin/users`,
    impersonation: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/super-admin/impersonation`,
    impersonationLaunch: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/super-admin/impersonation/launch`,
    userDetail: (lang: SupportedLanguage = DEFAULT_LANGUAGE, id: number | string = ':id') => `/${lang}/super-admin/users/${id}`,
    adminManagement: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/super-admin/admin-management`,
    teamNetwork: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/super-admin/team-network`,
    biosBlacklist: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/super-admin/bios-blacklist`,
    biosHistory: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/super-admin/bios-history`,
    biosDetails: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/super-admin/bios-details`,
    biosDetail: (lang: SupportedLanguage = DEFAULT_LANGUAGE, biosId: string | number = ':biosId') => `/${lang}/super-admin/bios-details/${encodeURIComponent(String(biosId))}`,
    biosConflicts: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/super-admin/bios-conflicts`,
    biosChangeRequests: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/super-admin/bios-change-requests`,
    usernameManagement: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/super-admin/admin-management`,
    securityLocks: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/super-admin/security-locks`,
    financialReports: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/super-admin/reports`,
    reports: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/super-admin/reports`,
    programLogs: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/super-admin/program-logs`,
    resellerPayments: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/super-admin/reseller-payments`,
    resellerPaymentDetail: (lang: SupportedLanguage = DEFAULT_LANGUAGE, resellerId: number | string = ':resellerId') => `/${lang}/super-admin/reseller-payments/${resellerId}`,
    resellerPaymentsManagerParentCustomers: (lang: SupportedLanguage = DEFAULT_LANGUAGE, managerParentId: number | string = ':managerParentId') => `/${lang}/super-admin/reseller-payments/manager-parent/${managerParentId}/customers`,
    ipAnalytics: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/super-admin/ip-analytics`,
    logs: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/super-admin/logs`,
    activity: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/super-admin/activity`,
    resellerLogs: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/super-admin/reseller-logs`,
    apiStatus: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/super-admin/api-status`,
    biosChangeAudit: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/super-admin/bios-change-audit`,
    settings: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/super-admin/settings`,
    profile: (lang: SupportedLanguage = DEFAULT_LANGUAGE) => `/${lang}/super-admin/profile`,
  },
}

export function getDashboardPath(role: UserRole, lang: SupportedLanguage = DEFAULT_LANGUAGE) {
  const segment = ROLE_DASHBOARD_SEGMENTS[role as keyof typeof ROLE_DASHBOARD_SEGMENTS]
  return segment ? `/${lang}/${segment}` : `/${lang}/login`
}



